# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12gKHIbMTxjzFIjyJ84xaEPBO1gB0LrBa
"""

#"n": "A água tem que ter o pH entre 6 e 9? " | fonte: https://www.siam.mg.gov.br/sla/download.pdf?idNorma=2747

ph=float(input('Digite o pH da água: '))

if 6<=ph<=9:
    print('A água está própria para consumo')
elif 0<=ph<6:
    print('A água está abaixo do pH ideal')
elif 14>=ph>9:
    print('A água está acima do pH ideal')
else:
    print('A água não está própria para consumo')